### ISSUE TITLE
Is it broken?

### ISSUE THREAD

**Issue by cukal** [fralau/repackage#1]
```
$ sudo pip install repackage
Collecting repackage
  Using cached https://files.pythonhosted.org/packages/ea/16/ee0f6f36c3f56cba4bbd1e6d7746300b2922ba3f005e9fee9b31a8c9d6b9/repackage-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-U2vNZ5/repackage/setup.py", line 20, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

Version 0.6 installs allright, but anything after that not: 

```
sudo pip install repackage==0.6
Collecting repackage==0.6
  Downloading https://files.pythonhosted.org/packages/53/b7/c147c02155f61cd6d716c962e1bf758d12d12076a9e121c10116063fe29e/repackage-0.6.tar.gz
Installing collected packages: repackage
  Found existing installation: repackage 0.5
    Uninstalling repackage-0.5:
      Successfully uninstalled repackage-0.5
  Running setup.py install for repackage ... done
Successfully installed repackage-0.6
```

**Comment by fralau** [comment]
Version 0.7.3 should have been fixed.
